### PR TITLE
NPM RAWIFY

### PR DESCRIPTION
**Pull request by Kazathur92**
I cursor'd every single one of my updates in shoppingCart.. which apparently was the only place I did updates :p which made it quick and easy to fix, there are 2 methods there that have not been rawified, but I think Rich wrote those, so I didnt touch them :) 

UPDATE** I fixed the errors that popped up at retro, it now filters by checking if the items have an deletedOn on all searches, and allows you to view an empty order history without breaking in user settings. Please pull and test and comment a thumbs up on your comments below if you approve this update.

### CODE REVIEW

**Review by Andrew-Herring — APPROVED** [review]
Nice job! 🥇

**Review by jessicabarnett8219 — APPROVED** [review]
Looks good!

**Review by rjlancaster — APPROVED** [review]
👍 looks good!

**Comment by jessicabarnett8219** [comment]
Looks like it's fixed! Good job! 👍

**Review by rjlancaster — APPROVED** [review]
👍 RAWK!  Merge it!

**Pull request merged**
