### PR TITLE
Sell product

### PR DESCRIPTION
**Pull request by Andrew-Herring**
- User can click on the sell product button on the nav bar, the item will be added to the database
- User will see a form to fill out to add a product to the database

To Test
- Navigate to localhost:8000/sell
- fill out the new product form
- click submit and check the database to see the item

!!!User and customer must have the same id!!!

items do no appear in the app currently

### CODE REVIEW

**Comment by jessicabarnett8219** [comment]
Looks great! Just missing the part where it should redirect to the product detail page instead of index.

**Comment by jessicabarnett8219** [comment]
ecomm:productDetail instead of ecomm:index

**Comment by jessicabarnett8219** [comment]
Also a docstring

**Comment by Kazathur92** [comment]
Other than it not accepting decimals on price it works great 👍 ✌️ :D

**Comment by jessicabarnett8219** [comment]
👍

**Pull request merged**
